#!/bin/bash
# One-time setup for StreamerIsolate.
#
# Creates the Python environment, fetches the models, and registers the native
# messaging host so the browser extension can start the backend itself. After
# this, using StreamerIsolate never involves a terminal.
#
#   ./scripts/install.sh                      # Firefox (+ Chrome if ID given)
#   ./scripts/install.sh <chrome-extension-id>
#
# The Chrome extension ID is shown on chrome://extensions with Developer mode
# on. Firefox needs no ID -- the extension declares a fixed one.

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VENV="$PROJECT_ROOT/.venv"
HOST_NAME="com.angusa1210.streamerisolate"
FIREFOX_EXT_ID="streamerisolate@angusa1210.github.io"
CHROME_EXT_ID="${1:-}"

echo "==> StreamerIsolate setup"
echo "    project: $PROJECT_ROOT"

# --- 1. Python environment -------------------------------------------------
PYTHON=""
for candidate in python3.12 python3.11 python3.10 /opt/homebrew/bin/python3.12; do
  if command -v "$candidate" >/dev/null 2>&1; then PYTHON="$candidate"; break; fi
done
if [ -z "$PYTHON" ]; then
  echo "ERROR: needs Python 3.10 or newer (macOS's built-in 3.9 is too old for PyTorch)." >&2
  echo "       Install it with:  brew install python@3.12" >&2
  exit 1
fi

if [ ! -x "$VENV/bin/python" ]; then
  echo "==> Creating virtual environment ($($PYTHON --version))"
  "$PYTHON" -m venv "$VENV"
else
  echo "==> Reusing existing virtual environment"
fi

echo "==> Installing dependencies (this can take several minutes the first time)"
"$VENV/bin/pip" install --quiet --upgrade pip
"$VENV/bin/pip" install --quiet -e "$PROJECT_ROOT"

# --- 2. Models -------------------------------------------------------------
# The classifier's package downloads its checkpoint with wget, which macOS
# doesn't ship, so fetch it here with curl instead. Demucs fetches its own
# weights fine on first run.
PANNS_DIR="$HOME/panns_data"
PANNS_CKPT="$PANNS_DIR/Cnn14_mAP=0.431.pth"
PANNS_LABELS="$PANNS_DIR/class_labels_indices.csv"
mkdir -p "$PANNS_DIR"

if [ ! -f "$PANNS_LABELS" ]; then
  echo "==> Downloading classifier labels"
  curl -fsSL -o "$PANNS_LABELS" \
    "http://storage.googleapis.com/us_audioset/youtube_corpus/v1/csv/class_labels_indices.csv"
fi

# 3e8 is the size the classifier package itself treats as "complete".
if [ ! -f "$PANNS_CKPT" ] || [ "$(stat -f%z "$PANNS_CKPT")" -lt 300000000 ]; then
  echo "==> Downloading classifier model (~327MB, resumable)"
  for _ in $(seq 1 20); do
    size=$(stat -f%z "$PANNS_CKPT" 2>/dev/null || echo 0)
    [ "$size" -ge 327428481 ] && break
    curl -fsSL -C - -o "$PANNS_CKPT" --max-time 120 \
      "https://zenodo.org/record/3987831/files/Cnn14_mAP%3D0.431.pth?download=1" || true
  done
  if [ "$(stat -f%z "$PANNS_CKPT" 2>/dev/null || echo 0)" -lt 300000000 ]; then
    echo "ERROR: classifier model download incomplete. Re-run this script to resume." >&2
    exit 1
  fi
fi

# --- 3. Native messaging host ---------------------------------------------
LAUNCHER="$PROJECT_ROOT/native-host/run-host.sh"
cat > "$LAUNCHER" <<LAUNCHER_EOF
#!/bin/sh
# Generated by scripts/install.sh -- absolute paths are required here because
# browsers launch this directly, with no shell environment to speak of.
exec "$VENV/bin/python" "$PROJECT_ROOT/native-host/streamerisolate_host.py"
LAUNCHER_EOF
chmod +x "$LAUNCHER"

write_manifest() {
  local target_dir="$1" browser="$2" allow_key="$3" allow_value="$4"
  mkdir -p "$target_dir"
  cat > "$target_dir/$HOST_NAME.json" <<MANIFEST_EOF
{
  "name": "$HOST_NAME",
  "description": "Starts the StreamerIsolate backend on demand",
  "path": "$LAUNCHER",
  "type": "stdio",
  "$allow_key": [$allow_value]
}
MANIFEST_EOF
  echo "    registered for $browser"
}

echo "==> Registering native messaging host"
write_manifest "$HOME/Library/Application Support/Mozilla/NativeMessagingHosts" \
  "Firefox" "allowed_extensions" "\"$FIREFOX_EXT_ID\""

if [ -n "$CHROME_EXT_ID" ]; then
  for chrome_dir in \
    "$HOME/Library/Application Support/Google/Chrome/NativeMessagingHosts" \
    "$HOME/Library/Application Support/Chromium/NativeMessagingHosts"; do
    [ -d "$(dirname "$chrome_dir")" ] && write_manifest "$chrome_dir" "Chrome" \
      "allowed_origins" "\"chrome-extension://$CHROME_EXT_ID/\""
  done
else
  echo "    skipped Chrome (no extension ID given)"
fi

echo
echo "==> Done."
echo
echo "Next steps:"
echo "  Firefox:  about:debugging#/runtime/this-firefox -> Load Temporary Add-on"
echo "            -> pick extension-firefox/manifest.json"
echo "  Chrome:   chrome://extensions -> Developer mode -> Load unpacked"
echo "            -> pick extension-chrome/"
if [ -z "$CHROME_EXT_ID" ]; then
  echo
  echo "  For Chrome, re-run with the extension ID shown on chrome://extensions:"
  echo "      ./scripts/install.sh <chrome-extension-id>"
fi
echo
echo "Then just click the extension icon -- it starts the backend for you."
